<a href="https://colab.research.google.com/github/Page0526/Pytorch-crash-course/blob/main/Learning_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 00. Pytorch Fundamentals

In [ ]:
import torch
torch.__version__

'2.2.1+cu121'

In [ ]:
# tensor: bieu dien data theo numerical way
# eg: bieu dien 1 anh vs shape [3, 224, 224] ~ [color_chanel, height, width]
# scalar: single number, zero dimension tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # check dimension

0

In [ ]:
scalar.item() # get python number trong tensors (chi lam viec vs one-element tensor)

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # trick: count the square brackets '['

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9296, 0.5958, 0.0293, 0.0137],
         [0.7894, 0.1203, 0.1236, 0.0576],
         [0.5232, 0.1367, 0.7072, 0.1851]]),
 torch.float32)

In [ ]:
image = torch.rand(size=(224, 224, 3))
image.shape, image.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
image

tensor([[[0.1272, 0.9252, 0.1634],
         [0.3393, 0.2978, 0.6300],
         [0.1564, 0.2200, 0.1981],
         ...,
         [0.3037, 0.4592, 0.6513],
         [0.0413, 0.4125, 0.8801],
         [0.7050, 0.3031, 0.1066]],

        [[0.4330, 0.6732, 0.1491],
         [0.8081, 0.4646, 0.4406],
         [0.2769, 0.5228, 0.3257],
         ...,
         [0.0445, 0.9304, 0.6234],
         [0.7728, 0.0087, 0.8461],
         [0.1484, 0.3669, 0.4868]],

        [[0.6710, 0.7224, 0.7078],
         [0.0888, 0.8122, 0.4096],
         [0.5658, 0.9111, 0.9351],
         ...,
         [0.8970, 0.8655, 0.0599],
         [0.1695, 0.7814, 0.9653],
         [0.3551, 0.4429, 0.0575]],

        ...,

        [[0.9102, 0.0174, 0.9940],
         [0.4532, 0.9148, 0.4508],
         [0.7107, 0.1150, 0.5716],
         ...,
         [0.0296, 0.5831, 0.5303],
         [0.3361, 0.0198, 0.3934],
         [0.1728, 0.2726, 0.2742]],

        [[0.2630, 0.8988, 0.4971],
         [0.6230, 0.9112, 0.8117],
         [0.

In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1)

In [ ]:
zero_to_ten
zero_to_ten.ndim, zero_to_ten.shape

(1, torch.Size([10]))

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6906, 0.0098, 0.1065, 0.4366],
        [0.7396, 0.8049, 0.5723, 0.9769],
        [0.8560, 0.2698, 0.1739, 0.8272]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensors operations)

### Basic operations
Basic operations: Addition, Subtraction, Multiplication, Division, Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
add = tensor + 10 # +
mul = tensor * 10 # *
sub = tensor - 10 # -
print(add, mul, sub)

tensor([11, 12, 13]) tensor([10, 20, 30]) tensor([-9, -8, -7])


In [ ]:
torch.mul(tensor, 10) # torch.mul() or torch.multiply() is ok

tensor([10, 20, 30])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

### Matrix multiplication
denote: @
syntax: torch.matmul()

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
mul

tensor([10, 20, 30])

In [ ]:
print(torch.transpose(mul, 0, -1)) # or tensor.T
add_transpose = add.T
add_transpose.shape, add.shape

tensor([10, 20, 30])


(torch.Size([3]), torch.Size([3]))

In [ ]:
x = torch.rand(size=(2, 3))
x_transpose = torch.transpose(x, 1, 0)
print(x_transpose.shape)
x, x_transpose

torch.Size([3, 2])


(tensor([[0.7901, 0.9818, 0.2866],
         [0.6204, 0.7683, 0.0154]]),
 tensor([[0.7901, 0.6204],
         [0.9818, 0.7683],
         [0.2866, 0.0154]]))

In [ ]:
x_transpose_1 = torch.transpose(x, -1, 0)
print(x_transpose_1.shape)
x_transpose_1

torch.Size([3, 2])


tensor([[0.7901, 0.6204],
        [0.9818, 0.7683],
        [0.2866, 0.0154]])

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

```torch.nn.Linear()```: feed-forward-layer for fully connected layer: $y = x.A^T+b$

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
# Stack tensors on top of each other
x_stacked_1 = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked_1

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Difference between two above code block is that:
dim=1: mean stacks from index 1 and dim=0 means stack from index 0

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed_1}")
print(f"New shape: {x_unsqueezed_1.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
