# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
torch.tensor([7, 7])

tensor([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor = torch.rand(1, 7)
# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor.T)

tensor([[1.7678]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_one = torch.rand(7, 1)
random_tensor_two = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor_one, random_tensor_two)

tensor([[0.4449, 0.2261, 0.3138, 0.1731, 0.1994, 0.0111, 0.0838],
        [0.6887, 0.3500, 0.4858, 0.2680, 0.3086, 0.0172, 0.1297],
        [0.0793, 0.0403, 0.0559, 0.0309, 0.0355, 0.0020, 0.0149],
        [0.1184, 0.0602, 0.0835, 0.0461, 0.0530, 0.0029, 0.0223],
        [0.2756, 0.1401, 0.1944, 0.1073, 0.1235, 0.0069, 0.0519],
        [0.5684, 0.2889, 0.4009, 0.2212, 0.2547, 0.0142, 0.1071],
        [0.4393, 0.2233, 0.3099, 0.1710, 0.1969, 0.0109, 0.0828]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
random_tensor_one = torch.rand(2, 3)
random_tensor_second = torch.rand(2, 3)
print(device)
print(random_tensor_one)
print(random_tensor_second)

cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
seven = torch.matmul(random_tensor_one, random_tensor_second.T)

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(seven.min())
# Find min
print(seven.max())

tensor(0.3647)
tensor(0.5617)


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print(seven.argmax())
# Find arg min
seven.argmin()

tensor(3)


tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
after = torch.squeeze(random_tensor)
# Print out tensors and their shapes
print(random_tensor)
random_tensor.shape
print(after)
after.shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


torch.Size([10])